name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
       # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install ruff pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: code

    - name: Lint with ruff
      run: |
            : # stop the build if there are Python syntax errors or undefined names
            ruff check code --format=github --select=E9,F63,F7,F82 .
            : # default set of ruff rules with GitHub Annotations
            ruff check code --format=github .
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
